//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SGA_ALMACEN> SGA_ALMACEN { get; set; }
        public DbSet<SGA_BOLETA> SGA_BOLETA { get; set; }
        public DbSet<SGA_CATEGORIA> SGA_CATEGORIA { get; set; }
        public DbSet<SGA_CLIENTE> SGA_CLIENTE { get; set; }
        public DbSet<SGA_COMUNA> SGA_COMUNA { get; set; }
        public DbSet<SGA_DETALLE_BOLETA> SGA_DETALLE_BOLETA { get; set; }
        public DbSet<SGA_DETALLE_ORDEN_COMPRA> SGA_DETALLE_ORDEN_COMPRA { get; set; }
        public DbSet<SGA_DETALLE_PRODUCTO> SGA_DETALLE_PRODUCTO { get; set; }
        public DbSet<SGA_MARCA> SGA_MARCA { get; set; }
        public DbSet<SGA_MENU> SGA_MENU { get; set; }
        public DbSet<SGA_ORDEN_COMPRA> SGA_ORDEN_COMPRA { get; set; }
        public DbSet<SGA_PERFIL> SGA_PERFIL { get; set; }
        public DbSet<SGA_PRODUCTO> SGA_PRODUCTO { get; set; }
        public DbSet<SGA_PROVEEDOR> SGA_PROVEEDOR { get; set; }
        public DbSet<SGA_USUARIO> SGA_USUARIO { get; set; }
    }
}
