//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_CLIENTE
    {
        public SGA_CLIENTE()
        {
            this.SGA_BOLETA = new HashSet<SGA_BOLETA>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_ALMACEN { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual SGA_ALMACEN SGA_ALMACEN { get; set; }
        public virtual ICollection<SGA_BOLETA> SGA_BOLETA { get; set; }
    }
}
