//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_PRODUCTO
    {
        public SGA_PRODUCTO()
        {
            this.SGA_DETALLE_ORDEN_COMPRA = new HashSet<SGA_DETALLE_ORDEN_COMPRA>();
            this.SGA_DETALLE_PRODUCTO = new HashSet<SGA_DETALLE_PRODUCTO>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_MARCA { get; set; }
    
        public virtual ICollection<SGA_DETALLE_ORDEN_COMPRA> SGA_DETALLE_ORDEN_COMPRA { get; set; }
        public virtual ICollection<SGA_DETALLE_PRODUCTO> SGA_DETALLE_PRODUCTO { get; set; }
        public virtual SGA_MARCA SGA_MARCA { get; set; }
    }
}
