//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_CATEGORIA
    {
        public SGA_CATEGORIA()
        {
            this.SGA_ALMACEN = new HashSet<SGA_ALMACEN>();
            this.SGA_MARCA = new HashSet<SGA_MARCA>();
        }
    
        public decimal ID_CATEGORIA { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<SGA_ALMACEN> SGA_ALMACEN { get; set; }
        public virtual ICollection<SGA_MARCA> SGA_MARCA { get; set; }
    }
}
