//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_DETALLE_PRODUCTO
    {
        public SGA_DETALLE_PRODUCTO()
        {
            this.SGA_DETALLE_BOLETA = new HashSet<SGA_DETALLE_BOLETA>();
        }
    
        public string COD_BARRA { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCIDAD { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<SGA_DETALLE_BOLETA> SGA_DETALLE_BOLETA { get; set; }
        public virtual SGA_PRODUCTO SGA_PRODUCTO { get; set; }
    }
}
