//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_ALMACEN
    {
        public SGA_ALMACEN()
        {
            this.SGA_ORDEN_COMPRA = new HashSet<SGA_ORDEN_COMPRA>();
            this.SGA_BOLETA = new HashSet<SGA_BOLETA>();
            this.SGA_CLIENTE = new HashSet<SGA_CLIENTE>();
            this.SGA_PROVEEDOR = new HashSet<SGA_PROVEEDOR>();
            this.SGA_USUARIO = new HashSet<SGA_USUARIO>();
        }
    
        public decimal ID_ALMACEN { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_CATEGORIA { get; set; }
        public string DIRECCION { get; set; }
        public decimal ID_COMUNA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<SGA_ORDEN_COMPRA> SGA_ORDEN_COMPRA { get; set; }
        public virtual ICollection<SGA_BOLETA> SGA_BOLETA { get; set; }
        public virtual ICollection<SGA_CLIENTE> SGA_CLIENTE { get; set; }
        public virtual ICollection<SGA_PROVEEDOR> SGA_PROVEEDOR { get; set; }
        public virtual ICollection<SGA_USUARIO> SGA_USUARIO { get; set; }
        public virtual SGA_CATEGORIA SGA_CATEGORIA { get; set; }
        public virtual SGA_COMUNA SGA_COMUNA { get; set; }
    }
}
