//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_MENU
    {
        public SGA_MENU()
        {
            this.SGA_PERFIL = new HashSet<SGA_PERFIL>();
        }
    
        public decimal ID_MENU { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PADRE_MENU { get; set; }
        public Nullable<decimal> DESTINO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<SGA_PERFIL> SGA_PERFIL { get; set; }
    }
}
