//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_USUARIO
    {
        public SGA_USUARIO()
        {
            this.SGA_BOLETA = new HashSet<SGA_BOLETA>();
            this.SGA_ORDEN_COMPRA = new HashSet<SGA_ORDEN_COMPRA>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASS { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_PERFIL { get; set; }
        public decimal ID_ALMACEN { get; set; }
    
        public virtual SGA_ALMACEN SGA_ALMACEN { get; set; }
        public virtual ICollection<SGA_BOLETA> SGA_BOLETA { get; set; }
        public virtual ICollection<SGA_ORDEN_COMPRA> SGA_ORDEN_COMPRA { get; set; }
        public virtual SGA_PERFIL SGA_PERFIL { get; set; }
    }
}
