//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_DETALLE_BOLETA
    {
        public decimal ID_DETALLE_BOLETA { get; set; }
        public decimal ID_BOLETA { get; set; }
        public string COD_BARRA { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
    
        public virtual SGA_BOLETA SGA_BOLETA { get; set; }
        public virtual SGA_DETALLE_PRODUCTO SGA_DETALLE_PRODUCTO { get; set; }
    }
}
