//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_MARCA
    {
        public SGA_MARCA()
        {
            this.SGA_PRODUCTO = new HashSet<SGA_PRODUCTO>();
        }
    
        public decimal ID_MARCA { get; set; }
        public string MARCA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> ID_CATEGORIA { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
    
        public virtual SGA_CATEGORIA SGA_CATEGORIA { get; set; }
        public virtual ICollection<SGA_PRODUCTO> SGA_PRODUCTO { get; set; }
        public virtual SGA_PROVEEDOR SGA_PROVEEDOR { get; set; }
    }
}
