//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_DETALLE_ORDEN_COMPRA
    {
        public decimal ID_DETALLE_ORDEN_COMPRA { get; set; }
        public decimal ID_ORDEN_COMPRA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
    
        public virtual SGA_ORDEN_COMPRA SGA_ORDEN_COMPRA { get; set; }
        public virtual SGA_PRODUCTO SGA_PRODUCTO { get; set; }
    }
}
