//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_ORDEN_COMPRA
    {
        public SGA_ORDEN_COMPRA()
        {
            this.SGA_DETALLE_ORDEN_COMPRA = new HashSet<SGA_DETALLE_ORDEN_COMPRA>();
        }
    
        public decimal ID_ORDEN_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_ORDEN_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_USUARIO { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public decimal ID_ALMACEN { get; set; }
    
        public virtual SGA_ALMACEN SGA_ALMACEN { get; set; }
        public virtual ICollection<SGA_DETALLE_ORDEN_COMPRA> SGA_DETALLE_ORDEN_COMPRA { get; set; }
        public virtual SGA_PROVEEDOR SGA_PROVEEDOR { get; set; }
        public virtual SGA_USUARIO SGA_USUARIO { get; set; }
    }
}
