//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_COMUNA
    {
        public SGA_COMUNA()
        {
            this.SGA_ALMACEN = new HashSet<SGA_ALMACEN>();
            this.SGA_PROVEEDOR = new HashSet<SGA_PROVEEDOR>();
        }
    
        public decimal ID_COMUNA { get; set; }
        public string COMUNA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<SGA_ALMACEN> SGA_ALMACEN { get; set; }
        public virtual ICollection<SGA_PROVEEDOR> SGA_PROVEEDOR { get; set; }
    }
}
